version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build-metaschema:
    working_directory: ~/oscal-metaschema # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers

    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - run:
          name: Get Saxon
          command: mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get -DartifactId=Saxon-HE -DgroupId=net.sf.saxon -Dversion=9.9.0-1
      - run:
          name: Generate OSCAL Catalog Artifacts
          working_directory: ~/oscal-metaschema/schema/metaschema
          command: bash ./run-metaschema.sh ./oscal-catalog-metaschema.xml catalog
          environment:
            SAXON: /home/circleci/.m2/repository/net/sf/saxon/Saxon-HE/9.9.0-1/Saxon-HE-9.9.0-1.jar
      - run:
          name: Generate OSCAL Profile Artifacts
          working_directory: ~/oscal-metaschema/schema/metaschema
          command: bash ./run-metaschema.sh ./oscal-profile-metaschema.xml profile
          environment:
            SAXON: /home/circleci/.m2/repository/net/sf/saxon/Saxon-HE/9.9.0-1/Saxon-HE-9.9.0-1.jar
      - run:   
          name: List Generated OSCAL Catalog Artifacts
          working_directory: ~/oscal-metaschema
          command: git status
      - deploy:
          name: Commit Artifacts
          working_directory: ~/oscal-metaschema
          command: |
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "Deploying built artifacts [ci skip]"
            git push
  build-docs:
    working_directory: ~/oscal-docs # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/ruby:2.3.8-jessie-node

    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - run:
          name: Install Bundler
          command: |
            cd ~/oscal-docs/docs
            gem install bundler
            bundle install
      - run:
          name: Middleman exec
          command: |
            cd ~/oscal-docs/docs
            bundle exec middleman build --clean
      - run:
          name: Run deploy script
          command: |
            cd ~/oscal-docs/docs
            bash ./deploy.sh -v -m "Deploying site [ci skip]"
workflows:
  version: 2
  build:
    jobs:
      - build-metaschema
      - build-docs:
          requires:
            - build-metaschema
