baseURL: https://pages.nist.gov/OSCAL/
title: "My First Site"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "uswds"
enableGitInfo: true
enableRobotsTXT: true
params:
  header:
    project_shortname: "OSCAL"
    project_name: "OSCAL: the Open Security Controls Assessment Language"
menu:
  secondary:
  - name: Get involved
    url: /contribute/
  - name: Contact Us
    url: /contact/
  - name: Github
    url: https://github.com/usnistgov/OSCAL
