on: [push, pull_request]
name: Release OSCAL tools container image
env:
  HOME_REPO: oscal-club/oscal
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  release-image:
    name: Build and publish the container image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # if: github.repository == env.HOME_REPO
        with:
          name: Check out code
          id: setup-checkout
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
      - name: Set up environment
        id: setup-env
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${RELEASE_TAG#"v"}"
          RELEASE_NAME="oscal-${RELEASE_VERSION}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - uses: redhat-actions/buildah-build@v2
        with:
          name: Build image from Dockerfile
          id: image-build
          image: ghcr.io/${{ env.HOME_REPO }}/cli
          tags: ${{ github.sha }} ${{ env.RELEASE_VERSION }} latest
          containerfiles: ./build/Dockerfile
          build_args: |
            saxonversion=9.9.0-1
            hugoversion=0.69.2
            calabashversion=1.3.2-100
      - uses: redhat-actions/push-to-registry@v2
        with:
          name: Publish Image to GitHub Container Registry
          id: image-push
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ env.OSCAL_HOME }}
