on: [push, pull_request]
name: Release OSCAL tools container image
env:
  HOME_REPO: oscal-club/oscal
  IMAGE_NAME: cli
  SAXON_VERSION: 9.9.0-1
  HUGO_VERSION: 0.69.2
  CALABASH_VERSION: 1.3.2-100
  RAW_REPO: ${{ github.repository }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  release-image:
    name: Build and publish the container image
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        id: setup-checkout
        uses: actions/checkout@v2
        # if: env.REPO == env.HOME_REPO
        with:
          path: ${{ env.OSCAL_HOME }}
          submodules: recursive
      - name: Set up environment
        id: setup-env
        run: |
          RELEASE_TAG="${GITHUB_REF#refs/*/}"
          RELEASE_VERSION="${RELEASE_TAG#"v"}"
          RELEASE_NAME="oscal-${RELEASE_VERSION}"
          echo "REPO=${RAW_REPO,,}" >>${GITHUB_ENV}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: Build image from Dockerfile
        id: image-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }} ${{ env.RELEASE_VERSION }} latest
          containerfiles: ./build/Dockerfile
          oci: true
          build-args: |
            saxonversion=${{ env.SAXON_VERSION }}
            hugoversion=${{ env.HUGO_VERSION }}
            calabashversion=${{ env.CALABASH_VERSION }}
          extra-args: |
            --ignorefile .dockerignore
      - name: Publish Image to GitHub Container Registry
        id: image-push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.image-build.outputs.image }}
          tags: ${{ steps.image-build.outputs.tags }}
          registry: ghcr.io/${{ env.REPO }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
