name: OSCAL CI/CD
on:
  push:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  pull_request:
    branches:
      - main
      - develop
      - "feature-*"
      - "release-*"
  workflow_dispatch:
jobs:
  checks:
    name: Status Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381
        with:
          node-version-file: "build/.nvmrc"
          cache: "npm"
          cache-dependency-path: "build/package-lock.json"
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils
      - name: Run all pipelines
        run: |
          make --keep-going all
        working-directory: build
