name: OSCAL CI/CD
on:
  push:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
  pull_request:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
  workflow_dispatch:
jobs:
  validate-repo-markdown:
    uses: ./.github/workflows/workflow-validate-repo-markdown.yml
  validate-metaschema-artifacts:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/workflow-generate-metaschema-resources.yml
    with:
      commit_resources: false
  push-metaschema-artifacts:
    if: github.event_name == 'push'
    uses: ./.github/workflows/workflow-generate-metaschema-resources.yml
    with:
      commit_resources: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}
