name: Validate Repo Markdown
on:
  workflow_call:
    inputs:
      create_issue:
        description: "create new GitHub issue if broken links found"
        required: false
        default: false
        type: boolean
jobs:
  validate-repo-markdown:
    name: Validate Repo Markdown
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: recursive
      - name: Set up NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version-file: "build/.nvmrc"
          cache: "npm"
          cache-dependency-path: "build/package-lock.json"
      - name: Perform link checking
        run: |
          make linkcheck
        working-directory: build
        id: linkchecker
      - name: Create issue if bad links detected in repo
        if: failure() && inputs.create_issue == true
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v3.0.0
        with:
          title: Scheduled Check of Markdown Documents Found Bad Hyperlinks
          content-filepath: mlc_report.log
          labels: |
            bug
            Scope: Documentation
